### ISSUE TITLE
Feature Request:  Allow racers to have two Twitch accounts linked to profile

### ISSUE THREAD

**Issue by fcoughlin** [racetimeGG/racetime-app#185] opened 2022-10-13 20:45 UTC
Some racers use alt accounts when streaming to Twitch (for example, when racing in a restreamed race to not affect Twitch viewer counts for partner stats/pushes).  However, in the current system, this requires the user to log out of their Twitch account, log in as the alt, THEN change the stream in racetime (all before joining the race), then switching it back the next time.  This is especially important for races in categories that require streaming to ready up.

It would be much easier to just have two accounts linked, and let the user select in their profile which one should be active.  I know it may not be a trivial feature, but would be a significant QoL improvement.

**Comment by deains** [comment] 2022-10-14 08:05
This is a duplicate of #20

**Closed by deains** 2022-10-14 08:05 UTC

**Comment by deains** [comment] 2022-10-14 08:06
To note though, the user would have to manually switch Twitch accounts on racetime still. Polling several Twitch accounts per user per race would eshaust our API limits.
